<?php
//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
    return [
        "db_configs"=>[
            'host'=>'digitadusersdb.cx0dfxutvhub.us-east-2.rds.amazonaws.com',
            'user'=>'theadmin_at_work',
            'password'=>'therealadmin',
            'users_db'=>'digitadusersdb'
        ],
        "encryption_settings"=>[
            'method'=>'AES-192-ECB',
            'password'=>'akemshow_users_data_locker',
            'git_token'=>""
        ],
        "smtp_cred"=>[
            'username'=>'noreply@digitadooh.tech',
            'password'=>'emmaculateakemAstheBoss@Me',
            'host'=>'wgh23.wghservers.com',
        ]
    ]
?>