<?php
    return [
        "db_configs"=>[
            'host'=>'digitadusersdb.cx0dfxutvhub.us-east-2.rds.amazonaws.com',
            'user'=>'theadmin_at_work',
            'password'=>'therealadmin',
            'users_db'=>'digitadusersdb'
        ],
        "encryption_settings"=>[
            'method'=>'AES-192-ECB',
            'password'=>'akemshow_users_data_locker'
        ],
        "smtp_cred"=>[
            'username'=>'no-reply@digitad-ooh.com',
            'password'=>'technoboss1000@me',
            'host'=>'smtp.google.com'
        ]
    ]
?>