<?php
	if($_SERVER['REQUEST_METHOD']=='GET'){
		$configs=include('../config.php');
		try{
			//connect to datatbase
		    $db_host=$configs['db_configs']['host'];
	        $db_user=$configs['db_configs']['user'];
	        $db_password=$configs['db_configs']['password'];
	        $db=$configs['db_configs']['users_db'];
	        $connection=mysqli_connect($db_host,$db_user,$db_password,$db);
	        if($connection){
	        	$sql="SELECT *FROM  city_screens_info";
				$result=mysqli_query($connection,$sql);
				if(!$result){
					throw new Exception(mysqli_error($result));	
				}
				if(mysqli_num_rows($result)>0){
					$screens_info=[];
					while($row=mysqli_fetch_assoc($result)){
						$city=$row['city'];
						$latitude=$row['latitude'];
						$longitude=$row['longitude'];
						$screen_name=$row['screen_name'];
						$resolution=$row['resolution'];
						$location=$row['location'];
						$country=$row['country'];
						$gdp=$row['country_gdp'];
						$price_per_day=$row['price'];
						$population=$row['population'];
						$state=$row['state'];
						$playlist=$row['playlist'];
						$runStart=$row['runStart'];
						$runEnd=$row['runEnd'];
						$deployed=$row['deployed'];
						$updatedDate=$row['updatedDate'];
						$numPlayedDays=$row['numPlayedDays'];
						$usedBudget=$row['usedBudget'];
						$expiredDate=$row['expiredDate'];
						$expired=$row['expired'];
						$img=$row['img'];
						$weekly_plan=$row['weekly_plan'];
						$monthly_plan=$row['monthly_plan'];
						$screen_data=[
							'country'=>$country,
							'city'=>$city,
							'latitude'=>$latitude,
							'longitude'=>$longitude,
							'screen_name'=>$screen_name,
							'resolution'=>$resolution,
							'location'=>$location,
							'gdp'=>$gdp,
							'price_per_day'=>$price_per_day,
							'population'=>$population,
							'state'=>$state,
							'playlist'=>$playlist,
							'runStart'=>$runStart,
							'runEnd'=>$runEnd,
							'deployed'=>$deployed,
							'updatedDate'=>$updatedDate,
							'numPlayedDays'=>$numPlayedDays,
							'usedBudget'=>$usedBudget,
							'expiredDate'=>$expiredDate,
							'numPlayedDays'=>$numPlayedDays,
							'expired'=>$expired,
							'img'=>$img,
							'weekly_plan'=>$weekly_plan,
							'monthly_plan'=>$monthly_plan
						];
						array_push($screens_info,$screen_data);
					}
					echo json_encode($screens_info);
				}
	        }
		}catch(Exception $e){
			print_r($e);
		}
	}
?>